const content=document.querySelector("#content"),win=document.querySelector("#window");
// Display only the tool artwork from the supplied sheet, excluding its headings.
const toolArtwork={files:[96,225],settings:[280,225],terminal:[639,225],apps:[1238,225],share:[1238,420]};
function applyToolArtwork(){
  document.querySelectorAll('[data-open]').forEach(button=>{
    const point=toolArtwork[button.dataset.open];
    const original=button.querySelector('img');
    if(!point||!original)return;
    const icon=document.createElement('span');
    icon.className='work-tool-icon';icon.setAttribute('aria-hidden','true');
    icon.style.backgroundPosition=`${-(point[0]-60)/3}px ${-(point[1]-60)/3}px`;
    original.replaceWith(icon);
  });
}
document.addEventListener('DOMContentLoaded',applyToolArtwork);
const titles={home:"Bienvenue sur TI-LEX Pro",settings:"Paramètres TI-LEX Pro",terminal:"Terminal TI-LEX Pro",files:"Mes fichiers · Téléchargements",apps:"Ouvrir avec TI-LEX"};
function message(title,body){document.querySelector("#message-title").textContent=title;document.querySelector("#message-body").textContent=body;document.querySelector("#message").showModal()}
function openApp(name){win.hidden=false;document.querySelector("#window-title").textContent=titles[name];({home,settings,terminal,files,apps}[name]||home)()}
document.addEventListener("click",e=>{const b=e.target.closest("[data-open]");if(b)openApp(b.dataset.open)});
document.querySelector("#close").onclick=document.querySelector("#minimize").onclick=()=>win.hidden=true;
document.querySelector("#maximize").onclick=()=>win.classList.toggle("full");
document.querySelector("#lock").onclick=()=>document.querySelector("#login").hidden=false;
document.querySelector("#unlock").onclick=()=>document.querySelector("#login").hidden=true;
function clock(){document.querySelector("#clock").textContent=new Date().toLocaleTimeString("fr-CA",{hour:"2-digit",minute:"2-digit"})}clock();setInterval(clock,30000);
function home(){content.innerHTML='<div class="home"><p class="eyebrow">VOTRE NOUVEL ESPACE DE TRAVAIL</p><h2>La liberté de Linux.<br>La simplicité de TI-LEX.</h2><p class="lead">Un bureau pour créer, explorer et travailler. Vos applications et vos réglages sont toujours à portée de clic.</p><div class="home-grid"><button class="home-card" data-open="settings"><img src="assets/settings.svg" alt=""><strong>Un bureau à votre image</strong><span>Réseau, son, apparence et matériel</span></button><button class="home-card" data-open="terminal"><img src="assets/terminal.svg" alt=""><strong>Un terminal, tout le potentiel</strong><span>Python, Git et vos outils Linux</span></button><button class="home-card" data-open="files"><img src="assets/tools.svg" alt=""><strong>Ouvrir en quelques clics</strong><span>Découvrez le lanceur de ZIP</span></button></div><div class="home-bottom"><span>Explorez les fenêtres avec les icônes du bureau.</span><span class="pill">Aperçu interactif</span></div></div>'}
const groups={
"Connexions":[["Wi-Fi","NetworkManager","◉"],["Bluetooth","Blueman","ᛒ"],["Profils réseau / VPN","Connexions réseau","⇄"]],
"Bureau et matériel":[["Son et microphones","Volume et périphériques","♫"],["Webcam","Cheese","◉"],["Imprimantes","Configuration des imprimantes","▤"],["Écrans","Résolution et affichage","▣"],["Clavier","Disposition et raccourcis","⌨"],["Apparence","Thème, polices et icônes","◐"],["Fond du bureau","Personnaliser le fond","▧"],["Alimentation","Veille et batterie","ϟ"],["Scanner","Simple Scan","▱"]],
"Système":[["Disques","GNOME Disks","◫"],["Pare-feu","GUFW","◇"],["Processus","Gestionnaire des tâches","≋"],["Sauvegardes","Déjà Dup","↶"],["Journaux système","Diagnostic Linux","≡"]],
"Terminal et outils":[["Terminal TI-LEX","Bash et outils Linux","›_"],["Python","Développement","⌘"],["Éditeur de texte","Mousepad","✎"],["Sessions tmux","Sessions persistantes","⊞"],["Ouvrir une application","ZIP, AppImage et paquets","↗"],["Archives","Xarchiver","▤"],["Capture d’écran","Outil XFCE","⊡"]]};
function settings(selected="Connexions"){content.innerHTML='<div class="settings-layout"><nav class="sidebar" aria-label="Catégories"><p class="eyebrow">PARAMÈTRES</p>'+Object.keys(groups).map(g=>'<button class="'+(g===selected?"active":"")+'" data-category="'+g+'">'+g+'</button>').join("")+'</nav><div class="settings-main"><div class="settings-heading"><div><h2>'+selected+'</h2><span class="subtle">Les réglages de votre espace TI-LEX</span></div><span class="pill">Démo</span></div><input class="search" aria-label="Rechercher un réglage" placeholder="Rechercher un réglage…"><div class="tool-grid"></div><p class="subtle">Aperçu visuel : les outils système s’ouvriront dans la distribution Linux.</p></div></div>';
const render=q=>{const list=q?Object.values(groups).flat().filter(t=>t[0].toLowerCase().includes(q.toLowerCase())):groups[selected];const grid=content.querySelector(".tool-grid");grid.replaceChildren();for(const [title,sub,glyph]of list){const b=document.createElement("button");b.className="tool-card";b.innerHTML='<span class="glyph"></span><span><b></b><small></small></span><span class="arrow">›</span>';b.querySelector(".glyph").textContent=glyph;b.querySelector("b").textContent=title;b.querySelector("small").textContent=sub;b.onclick=()=>title==="Terminal TI-LEX"?openApp("terminal"):title==="Ouvrir une application"?openApp("apps"):message(title,"Dans TI-LEX Linux, ce bouton ouvre "+sub+". Cet aperçu web ne modifie aucun réglage de votre ordinateur.");grid.append(b)}};
render("");content.querySelector(".search").oninput=e=>render(e.target.value);content.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>settings(b.dataset.category))}
function terminal(){content.innerHTML='<div class="terminal"><p class="orange">TI-LEX PRO / TERMINAL</p><p class="term-hint">Démonstration · aucune commande exécutée sur votre ordinateur</p><p>Bienvenue. Essayez <span class="green">tilex aide</span>, <span class="green">tilex systeme</span> ou <span class="green">clear</span>.</p><div id="history"></div><form class="term-input"><label for="command" class="orange">visiteur@ti-lex:~ $</label><input id="command" autocomplete="off" spellcheck="false" aria-label="Commande de démonstration"></form></div>';const form=content.querySelector("form"),input=content.querySelector("input"),history=content.querySelector("#history");form.onsubmit=e=>{e.preventDefault();const value=input.value.trim();input.value="";if(value==="clear"){history.replaceChildren();return}const row=document.createElement("p");row.className="green";row.textContent="$ "+value;history.append(row);const out=document.createElement("p");const replies={"tilex aide":"Commandes de démonstration :\n  tilex systeme    Présentation du système\n  tilex reseau     Aperçu du réseau\n  tilex processus Aperçu des processus\n  tilex python    Outils de développement\n  clear           Effacer cet historique","tilex systeme":"Cible du projet : TI-LEX Pro · Debian 13 · amd64 · XFCE\nL’ISO reste à construire et à tester.","tilex reseau":"Dans Linux : ouvre nmcli et affiche vos interfaces.\nCet aperçu n’a accès à aucun périphérique réseau.","tilex processus":"Dans Linux : ouvre htop pour consulter les processus.","tilex python":"Dans Linux : ouvre Python 3. Git, pip, venv et les outils de développement sont prévus dans l’image."};out.textContent=replies[value]||"Commande non simulée. Tapez tilex aide. Le terminal réel sera disponible dans Linux.";history.append(out);input.scrollIntoView({block:"nearest"})};input.focus()}
function files(){content.innerHTML='<div class="files"><p class="eyebrow">MES FICHIERS</p><h2>Téléchargements</h2><p class="subtle">Essayez le clic droit sur l’archive, ou utilisez le bouton Ouvrir.</p><div class="file-row" id="zip"><img src="assets/folder.svg" alt=""><div><strong>Mon-application.zip</strong><small>Archive de démonstration · aucun téléchargement réel</small></div><button class="primary" id="open-zip">Ouvrir avec TI-LEX</button></div><div class="step"><b>1</b>Téléchargez une application Linux compatible.</div><div class="step"><b>2</b>Clic droit → Ouvrir avec TI-LEX.</div><div class="step"><b>3</b>Choisissez le programme, puis cliquez sur Ouvrir.</div><p class="subtle">ZIP, AppImage, scripts Python/Bash et paquets Debian.<br>Les applications Windows .exe ne sont pas prises en charge.</p></div>';content.querySelector("#open-zip").onclick=()=>openApp("apps");content.querySelector("#zip").ondblclick=()=>openApp("apps");content.querySelector("#zip").oncontextmenu=e=>{e.preventDefault();document.querySelector(".context")?.remove();const menu=document.createElement("div");menu.className="context";menu.style.left=Math.min(e.clientX,innerWidth-230)+"px";menu.style.top=Math.min(e.clientY,innerHeight-70)+"px";menu.innerHTML="<button>Ouvrir avec TI-LEX</button>";menu.querySelector("button").onclick=()=>{menu.remove();openApp("apps")};document.body.append(menu);setTimeout(()=>document.addEventListener("click",()=>menu.remove(),{once:true}),0)}}
function apps(){content.innerHTML='<div class="files"><p class="eyebrow">OUVERTURE SIMPLIFIÉE</p><h2>Votre application, sans terminal.</h2><p class="subtle">Parcours de démonstration du lanceur TI-LEX.</p><div class="file-row"><img src="assets/tools.svg" alt=""><div><strong>Mon-application.AppImage</strong><small>Exemple de programme trouvé dans le ZIP</small></div><span class="pill">Sélectionné</span></div><p class="subtle">Dans Linux, le ZIP est extrait dans un dossier dédié. Exécutez uniquement une application dont vous connaissez la provenance : elle aura accès aux fichiers de votre compte.</p><button class="primary" id="launch-demo">Ouvrir l’application de démonstration →</button><p class="subtle">Aucun fichier n’est extrait ni exécuté dans cet aperçu.</p></div>';content.querySelector("#launch-demo").onclick=()=>{content.innerHTML='<div class="app-ready"><img src="assets/logo.svg" alt=""><p class="eyebrow">PARCOURS TERMINÉ</p><h2>Et voilà. Sans commande à taper.</h2><p>Vous venez de parcourir la démonstration.<br>Dans Linux, TI-LEX lance le programme choisi.<br>Sa compatibilité dépend de son format et de ses dépendances.</p><button class="primary" data-open="files">Revenir aux fichiers</button></div>'}}
openApp("home");
// Transitions globales pour chaque fenêtre de l’aperçu.
const openAppInstant=openApp;
openApp=function(name){if(name==="share"){win.hidden=false;document.querySelector("#window-title").textContent=titles.share;share();}else{openAppInstant(name)}win.classList.remove("window-closing");win.classList.remove("window-opening");void win.offsetWidth;win.classList.add("window-opening");};
function closeWindowAnimated(){if(win.hidden)return;win.classList.remove("window-opening");win.classList.add("window-closing");setTimeout(()=>{win.hidden=true;win.classList.remove("window-closing");},420)}
document.querySelector("#close").onclick=closeWindowAnimated;
document.querySelector("#minimize").onclick=closeWindowAnimated;
const weather=document.createElement("button");weather.id="weather";weather.className="weather";weather.title="Météo locale";weather.innerHTML='<img src="assets/weather.svg" alt=""><span>--°C</span>';document.querySelector(".brand").before(weather);
weather.onclick=()=>message("Météo locale","Autorisez la localisation dans votre navigateur pour afficher la température de votre région.");
const shareShortcut=document.createElement("button");shareShortcut.dataset.open="share";shareShortcut.innerHTML='<img src="assets/tools.svg" alt=""><span>Partager téléphone</span>';document.querySelector(".desktop-icons").append(shareShortcut);
titles.share="Partager avec un téléphone";
function share(){const code=String(Math.floor(100000+Math.random()*900000));content.innerHTML='<div class="share-panel"><p class="eyebrow">PARTAGE LOCAL · WI-FI</p><h2>Connecter un téléphone</h2><p class="subtle">Sur le téléphone, ouvrez l’adresse locale affichée par TI-LEX puis saisissez ce code.</p><div class="share-code">'+code+'</div><div class="share-types"><span>Images</span><span>Fichiers</span><span>Vidéos</span><span>Musique</span></div><p class="subtle">Connexion directe par réseau local. Aucun Bluetooth requis. Le code expire après une courte période.</p><button class="primary" id="new-share">Générer un nouveau code</button></div>';content.querySelector("#new-share").onclick=share}
